# Generated by Django 6.0.7 on 2026-08-03 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaselot',
            name='remaining_amount',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
