# Generated by Django 6.0.7 on 2026-08-13 04:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_productvariant_productvari_product_6722a2_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GastoExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.IntegerField()),
                ('tipo', models.CharField(choices=[('envio', 'Envío'), ('bolsas', 'Bolsas'), ('regalo', 'Regalo'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('motivo', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gasto extra',
                'verbose_name_plural': 'Gastos extras',
                'db_table': 'gastoExtra',
                'ordering': ['-fecha'],
            },
        ),
    ]
